<a href="https://colab.research.google.com/github/GDVevo/GDVevo/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%E2%84%965_%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B8_%D0%BB%D0%BE%D0%B3%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Практическая работа №5. Линейная и логистическая регрессия**

## **Линейная регрессия**

###  **Задание №1. Прогнозирование продаж автомобилей**:

   - **Шаг 1**: Загрузите набор данных о продажах автомобилей, содержащий информацию о цене, возрасте, пробеге и других характеристиках.
     - **Совет**: Проверьте данные на наличие пропущенных значений и выбросов. Используйте `pandas` для обнаружения пропусков (`df.isnull().sum()`) и выбросов (например, с помощью метода межквартильного размаха - `df.boxplot()`).
     - **Совет**: Для пропущенных значений используйте стратегию заполнения средними значениями или медианой, чтобы минимизировать влияние на распределение данных (`df.fillna()`).

- Ссылка на набор данных: https://www.kaggle.com/datasets/gagandeep16/car-sales

In [ ]:
# Ваш код
import pandas as pd
import kagglehub
kagglehub.dataset_download("gagandeep16/car-sales")

df = pd.read_csv('/kaggle/input/car-sales/Car_sales.csv') # если вывел ошибку, запустить еще раз

df.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

   - **Шаг 2**: Проведите предварительный анализ данных:
     - Постройте гистограммы для каждого числового признака, чтобы понять их распределение.
     - Постройте диаграммы рассеяния для выявления зависимостей между признаками и целевой переменной (ценой).
     - **Совет**: Используйте корреляционную матрицу для выявления сильных линейных зависимостей между признаками.

In [5]:
# Ваш код
import matplotlib.pyplot as plt

   - **Шаг 3**: Разделите данные на обучающую и тестовую выборки (например, 70% на обучение и 30% на тестирование) с помощью `train_test_split` из `sklearn.model_selection`.

In [ ]:
# Ваш код
from sklearn.model_selection import train_test_split

   - **Шаг 4**: Постройте модель линейной регрессии для предсказания цены автомобиля.
     - Используйте библиотеку `scikit-learn` для создания и обучения модели с помощью `LinearRegression`.

In [3]:
# Ваш код
from sklearn.linear_model import LinearRegression

   - **Шаг 5**: Оцените качество модели с использованием метрик MSE и R².
     - Выведите значения метрик и интерпретируйте их. Обратите внимание на то, насколько хорошо ваша модель предсказывает цены.

In [ ]:
# Ваш код
from sklearn.metrics import mean_squared_error, r2_score

   - **Шаг 6**: Визуализируйте результаты:
     - Постройте график зависимости предсказанных цен от фактических.

In [ ]:
# Ваш код


### **Задание №2. Влияние погодных условий на урожайность**:

   - **Шаг 1**: Загрузите набор данных о погодных условиях и урожайности сельскохозяйственных культур.
     - **Совет**: Проверьте данные на наличие пропущенных значений и выбросов. Используйте стратегию заполнения пропусков средними значениями или медианой.

- Ссылка на набор данных: https://www.kaggle.com/datasets/waqi786/climate-change-impact-on-agriculture

In [8]:
# Ваш код
import pandas as pd
import kagglehub

kagglehub.dataset_download("waqi786/climate-change-impact-on-agriculture")

df = pd.read_csv('/kaggle/input/climate-change-impact-on-agriculture/climate_change_impact_on_agriculture_2024.csv')

df.head()

Using Colab cache for faster access to the 'climate-change-impact-on-agriculture' dataset.

   Year Country  ... Adaptation_Strategies Economic_Impact_Million_USD
0  2001   India  ...      Water Management                      808.13
1  2024   China  ...         Crop Rotation                      616.22
2  2001  France  ...      Water Management                      796.96
3  2001  Canada  ...         No Adaptation                      790.32
4  1998   India  ...         Crop Rotation                      401.72

[5 rows x 15 columns]

   - **Шаг 2**: Выполните анализ данных:
     - Постройте корреляционную матрицу для выявления зависимостей между признаками.
     - Постройте диаграммы рассеяния для ключевых признаков.
     - **Совет**: Удалите или преобразуйте признаки с низкой корреляцией с целевой переменной, чтобы улучшить модель.

In [ ]:
# Ваш код
import matplotlib.pyplot as plt

   - **Шаг 3**: Разделите данные на обучающую и тестовую выборки.

In [ ]:
# Ваш код
from sklearn.model_selection import train_test_split

   - **Шаг 4**: Постройте модель линейной регрессии для оценки влияния температуры и уровня осадков на урожайность.
     - Используйте библиотеку `scikit-learn` для создания и обучения модели.

In [ ]:
# Ваш код
from sklearn.linear_model import LinearRegression

   - **Шаг 5**: Проведите оценку точности модели.
     - Выведите значения метрик MSE и R² и интерпретируйте их.

In [ ]:
# Ваш код
from sklearn.metrics import mean_squared_error, r2_score

   - **Шаг 6**: Визуализируйте данные и результаты модели:
     - Постройте график зависимости предсказанных значений от фактических.

In [ ]:
# Ваш код

## **Логистическая регрессия**

### **Задание №3. Классификация клиентов банка**:

   - **Шаг 1**: Загрузите набор данных о клиентах банка, включающий данные о возрасте, доходе, кредитной истории и других характеристиках.
     - **Совет**: Проверьте данные на наличие пропущенных значений и выбросов. Используйте стратегию заполнения пропусков средними значениями или медианой.

- Ссылка на набор данных: https://www.kaggle.com/datasets/henriqueyamahata/bank-marketing/data

In [12]:
# Ваш код
import pandas as pd
import kagglehub

kagglehub.dataset_download("henriqueyamahata/bank-marketing")

df = pd.read_csv('/kaggle/input/bank-marketing/bank-additional-full.csv', sep = ';')

df.head()

Using Colab cache for faster access to the 'bank-marketing' dataset.

   age        job  marital  ... euribor3m nr.employed   y
0   56  housemaid  married  ...     4.857      5191.0  no
1   57   services  married  ...     4.857      5191.0  no
2   37   services  married  ...     4.857      5191.0  no
3   40     admin.  married  ...     4.857      5191.0  no
4   56   services  married  ...     4.857      5191.0  no

[5 rows x 21 columns]

   - **Шаг 2**: Проведите анализ данных и предобработку:
     - Закодируйте категориальные переменные с помощью `OneHotEncoder` или `pd.get_dummies`.
     - Нормализуйте числовые признаки с помощью `StandardScaler` для улучшения обучения модели.
     - **Совет**: Убедитесь, что все признаки имеют одинаковый масштаб, чтобы избежать доминирования одного признака над другими.

In [ ]:
# Ваш код
from sklearn.preprocessing import StandardScaler # вместо onehot используем get_dummies

   - **Шаг 3**: Разделите данные на обучающую и тестовую выборки.

In [ ]:
# Ваш код
from sklearn.model_selection import train_test_split

   - **Шаг 4**: Постройте модель логистической регрессии для предсказания вероятности открытия депозитного счета клиентом.
     - Используйте библиотеку `scikit-learn` для создания и обучения модели с помощью `LogisticRegression`.

In [ ]:
# Ваш код
from sklearn.linear_model import LogisticRegression

   - **Шаг 5**: Оцените качество модели с использованием метрик точности, полноты и F1-меры.
     - Выведите значения метрик и интерпретируйте их. Обратите внимание на баланс между точностью и полнотой.
    - Постройте матрицу ошибок с помощью `confusion_matrix` и визуализируйте ее с помощью `seaborn.heatmap`.

In [21]:
# Ваш код
from sklearn.metrics import precision_score, f1_score, recall_score, confusion_matrix
import seaborn as sns



   

   
   

   

   
   - **Шаг 6**: Визуализируйте ROC-кривую и вычислите AUC для оценки модели.
     - Используйте `roc_curve` и `auc` из `sklearn.metrics` для построения и расчета.

In [ ]:
# Ваш код
from sklearn.metrics import roc_curve, auc

### **Задание №4. Распознавание спама**:

   - **Шаг 1**: Загрузите набор данных с текстами электронных писем, маркированных как "спам" или "не спам".
     - **Совет**: Проверьте данные на наличие пропущенных значений и оцените, какие признаки могут быть важными для классификации.

- Ссылка на набор данных: https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

In [16]:
# Ваш код
import pandas as pd
import kagglehub

kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

df = pd.read_csv("/kaggle/input/sms-spam-collection-dataset/spam.csv", encoding="latin-1")

df = df.dropna(how="any", axis=1) # вот это возможно надо будет убрать, ибо в дальнейшем будем фиксить???
df.columns = ['target', 'message']

df.head()

Using Colab cache for faster access to the 'sms-spam-collection-dataset' dataset.

  target                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

   - **Шаг 2**: Выполните предварительную обработку текстов:
     - Выполните токенизацию и векторизацию с помощью `Word2Vec` или `Doc2Vec`.

In [18]:
# Ваш код
!pip install gensim
from gensim.models import Word2Vec

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 59.8 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

   - **Шаг 3**: Разделите данные на обучающую и тестовую выборки.

In [ ]:
# Ваш код
from sklearn.model_selection import train_test_split

   - **Шаг 4**: Постройте модель логистической регрессии для классификации писем на спам и не спам.
     - Используйте библиотеку `scikit-learn` для создания и обучения модели с помощью `LogisticRegression`.
     - Сравните результаты с моделью `MultinomialNB` *(Наивного Байеса)*

In [22]:
# Ваш код
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

   - **Шаг 5**: Оцените качество моделей с помощью матрицы ошибок и ROC-кривой.
     - Постройте матрицу ошибок с помощью `confusion_matrix` и визуализируйте ее с помощью `seaborn.heatmap`.
     - Постройте ROC-кривую и вычислите AUC.

In [ ]:
# Ваш код
from sklearn.metrics import confusion_matrix, roc_curve, auc
import seaborn as sns

   - **Шаг 6**: Визуализируйте результаты классификации и сравните их с исходными метками.
     - Приведите примеры писем, которые были неправильно классифицированы, и напишите возможные причины ошибок.

In [ ]:
# Ваш код
import matplotlib.pyplot as plt